---
#- include: with_no_proxy.yml
#  when: (https_proxy is not defined or https_proxy | trim == '') and (http_proxy is not defined or http_proxy | trim == '')
#
#- include: with_proxy.yml
#  when: https_proxy is defined and https_proxy | trim != '' and http_proxy is defined and http_proxy | trim != ''
- block:

  - name: Install Java JDK with proxy
    become: yes
    yum:
      name: "java-{{ jdk_version }}.0-openjdk-devel.{{ ansible_architecture }}"
      state: present
      disable_gpg_check: yes
    environment:
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"
      no_proxy: "{{ no_proxy }}"

  rescue:
    - name: Install Java JDK with proxy
      become: yes
      yum:
        name: "java-{{ jdk_version }}.0-openjdk-devel"
        state: present
        disable_gpg_check: yes
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"
        no_proxy: "{{ no_proxy }}"

- name: Update environment with path to JAVA_HOME
  become: yes
  lineinfile:
    dest: /etc/environment
    regexp: "^export JAVA_HOME"
    line: 'export JAVA_HOME={{ java_home }}'
    backup: yes

