---
- include: with_no_proxy.yml
  when: http_proxy is not defined and https_proxy is not defined

- include: with_proxy.yml
  when: http_proxy is defined and https_proxy is defined


- name: Update environment with path to JAVA_HOME
  become: yes
  lineinfile:
    dest: /etc/environment
    regexp: "^export JAVA_HOME"
    line: 'export JAVA_HOME={{ java_home }}'
    backup: yes

