---
- block:

  - name: Install Java JDK with proxy
    become: yes
    yum:
      name: "java-{{ jdk_version }}.0-openjdk-devel.{{ ansible_architecture }}"
      state: present
      disable_gpg_check: yes
    environment:
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"
      no_proxy: "{{ no_proxy }}"

  rescue:
    - name: Install Java JDK with proxy
      become: yes
      yum:
        name: "java-{{ jdk_version }}.0-openjdk-devel"
        state: present
        disable_gpg_check: yes
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"
        no_proxy: "{{ no_proxy }}"

